import pygame

pygame.mixer.init() #initialisation du mixeur    
pygame.mixer.music.load("musicMario.mp3")   # chargement de la musique
pygame.mixer.music.set_volume(0.1)  # ajustement du volume
pygame.mixer.music.play()   #la musique se lance à partir de cette ligne

#============================Le code du jeu est écrit ici :===================
#MON CODE .............................
#MON CODE ..............................
#MON CODE .............................
#MON CODE ..............................
#MON CODE .............................
#MON CODE ..............................
#=============================================================================

pygame.mixer.music.stop()  #la musique s'arrête à partir de cette ligne

